### ISSUE TITLE
Mint has problems syncing credentials

### ISSUE THREAD

**Issue by eit15** [zalando-stups/mint-worker#12] opened 2015-11-04 20:06 UTC
Yourturn shows the following error message:

mint has problems syncing credentials. Please check that all configured S3 buckets exist and give write access to mint-worker.
clojure.lang.ExceptionInfo: clj-http: status 406 {:status 406, :headers
{"Date" "Wed, 04 Nov 2015 17:52:00 GMT", "Content-Length" "115", "Content-Type" "text/plain; charset=utf-8", "Connection" "close"}
, :body "
{\"code\":406,\"message\":\"Failed to get data for LDAP user: Lookup of team DN returned 404\",\"reason\":\"Not Acceptable\"}
", :request-time 341, :trace-redirects ["(...)"], :orig-content-encoding nil}

The access rights for the bucket (...) seem to be OK. The problem is probably that the team of the AWS account does no longer exist in LDAP, because there was a team merge and so the team id in AWS and in LDAP no longer match.

**Comment by prayerslayer** [comment] 2015-11-05 07:10
Hi, I will close this issue as it is not a bug or a feature request but rather an operational problem. Please use our official support channels (Chat, Mail) for that kind of thing and provide some more details (e.g. team name would be beneficial here) so we can take care of it. Thank you!

**Closed as completed by prayerslayer** 2015-11-05 07:10 UTC

**Comment by eit15** [comment] 2015-11-05 08:39
This is just kafkaesque.

Am 05.11.15 KW44 um 08:10 schrieb Nikolaus Piccolotto:

> Hi, I will close this issue as it is not a bug or a feature request but rather an operational problem. Please use our official support channels (Chat, Mail) for that kind of thing and provide some more details (e.g. team name would be beneficial here) so we can take care of it. Thank you!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zalando-stups/mint-worker/issues/12#issuecomment-153974868

## 

Eberhard Iglhaut
Team Router & Composition
https://techwiki.zalando.net/display/~eiglhaut
